import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useRouter} from 'next/router'


function Home({movies}) {
   
  const router=useRouter()
  const handileClick=(id)=>{
     console.log(id)

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display:"grid" ,gridTemplateColumns:"300px 300px 300px ",justifyContent:"center" ,gap:"100px"}}>
        {
          movies.map((mov)=>{
            return (
              <div key={mov.id} style={{textAlign:"center"}}>
                <h4>{mov.original_title}</h4>
                <Image
     
                     src={mov. poster_path}
                     alt="Picture of the author"
                     width={300}
                     height={300}
                   />
      <button onClick={()=>handileClick(mov.id)}> view More...</button>
              </div>
            )
          })
        }
         
      </main>

    
    </div>
  )
}

export async function  getStaticProps(context) {


  const res = await fetch(`https://next-backend-orpin.vercel.app/movies`)
  const data = await res.json()
 
  return {
    props: {movies:data}, // will be passed to the page component as props
  }
}

export default Home